//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hexagon
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerSalary
    {
        public int ID { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedTime { get; set; }
    }
}
